---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Demo

## R

The [reticulate](https://rstudio.github.io/reticulate/) package allows using
Python from R and RStudio. Some key features work automatically.

```{r}
# You may want to specify which copy of Python reticulate chooses to bind to
readLines(here::here(".Renviron"))

reticulate::py_config()
```

## Python

[Anaconda](https://docs.continuum.io/anaconda/) is a collection of software for
data science with Python and R. It contains Python itself, many Python packages,
and a tool called `conda` that manages it all.

Example:

This packages came with Anaconda

```{python}
import nltk
import spacy
```

```{python}
sent = "Please book my flight to California."

tokenized_sent_nltk = nltk.sent_tokenize(sent)
[nltk.pos_tag(nltk.word_tokenize(word)) for word in tokenized_sent_nltk]

# This failed and I had to install en_core_web_sm with:
#   conda install -c conda-forge spacy-model-en_core_web_sm
nlp = spacy.load("en_core_web_sm")
spacy_doc = nlp(sent)

print(spacy_doc)

for token in spacy_doc:
    print(token.text, token.pos_)
```
